"""*** A GENERATED TEST THAT FAILS ON ITS FIRST RUN IS WORSE THAN NO TEST. ***

It is the difference between a patch and a nag, and this command only exists because `practices`
counts a proposed grain before recommending it. Reported from the field before that landed: 15
proposals, 0 held, `water_division` offered as the grain of a 1,045-row model with SEVEN distinct
values.
"""
from pathlib import Path

from dbt_assay import patch as pm

HELD = {"ok": (500, 500), "fan": (1045, 7)}


def _plan(patches, held=None, out="/tmp/_assay_patch_t"):
    return pm.plan(patches, held if held is not None else HELD, "9.9.9", Path(out))


def test_a_grain_that_holds_becomes_a_file():
    p = _plan([("ok", ["id"], "derived", 3, [])])[0]
    assert p.sql and "count(*) as n_rows" in p.sql
    assert "group by id" in p.sql
    assert "{{ ref('ok') }}" in p.sql
    assert "500" in p.sql, "the count that justified it belongs in the file"


def test_a_grain_that_does_not_hold_never_becomes_a_file():
    """1,045 rows over 7 distinct values. A test here fails immediately."""
    p = _plan([("fan", ["water_division"], "derived", 2, [])])[0]
    assert not p.sql
    assert "149x" in p.skipped


def test_an_uncounted_grain_is_refused_rather_than_assumed_to_pass():
    """*** AN ABSENT COUNT IS NOT A PASSING ONE. ***
    The defect this codebase has now found seven times, in the one command that writes files."""
    p = _plan([("never_counted", ["k"], "derived", 1, [])])[0]
    assert not p.sql
    assert "NOT COUNTED" in p.skipped


def test_a_grain_naming_a_column_the_model_does_not_emit_is_refused():
    p = _plan([("renamed", ["parcel_id"], "derived", 1, ["parcel_id"])])[0]
    assert not p.sql
    assert "does not emit" in p.skipped


def test_a_column_that_is_not_a_plain_identifier_is_refused_not_quoted():
    """A generated file is read less carefully than a written one. This is the wrong place to be
    clever with quoting."""
    p = _plan([("weird", ["a; drop table x"], "derived", 1, [])], held={"weird": (5, 5)})[0]
    assert not p.sql
    assert "plain identifier" in p.skipped


def test_it_never_overwrites_a_file_a_person_wrote(tmp_path):
    """*** THE ONE THING WORSE THAN A BAD GENERATED TEST IS ONE THAT ATE A GOOD HANDWRITTEN ONE.
    ***"""
    out = tmp_path / "assay"
    out.mkdir()
    mine = out / "unique_ok.sql"
    mine.write_text("-- mine, hand written\n")
    plans = pm.plan([("ok", ["id"], "derived", 1, [])], HELD, "9.9.9", out)
    n, blocked = pm.write(plans, out)
    assert n == 0 and len(blocked) == 1
    assert mine.read_text() == "-- mine, hand written\n"


def test_it_does_replace_a_file_it_wrote_itself(tmp_path):
    out = tmp_path / "assay"
    plans = pm.plan([("ok", ["id"], "derived", 1, [])], HELD, "9.9.9", out)
    assert pm.write(plans, out)[0] == 1
    plans2 = pm.plan([("ok", ["id", "source"], "derived", 1, [])], {"ok": (7, 7)}, "9.9.9", out)
    n, blocked = pm.write(plans2, out)
    assert n == 1 and not blocked
    assert "group by id, source" in (out / "unique_ok.sql").read_text()


def test_every_generated_file_says_what_justified_it():
    """A reader finding this file in six months must be able to tell what it is and whether to
    trust it, without finding assay."""
    p = _plan([("ok", ["id"], "derived", 3, [])])[0]
    for must in ("generated by assay", "assay:generated", "COUNTED it before writing",
                 "delete this file", "did not decide this was the RIGHT grain"):
        assert must in p.sql, must
