"""Tests assay writes, for grains it has counted.

*** A GENERATED TEST THAT FAILS ON ITS FIRST RUN IS WORSE THAN NO TEST. ***
It is the difference between a patch and a nag, and this command exists only because `practices`
now COUNTS a proposed grain through the project's own dbt before recommending it. Nothing is
written here for a grain that was not counted, or that was counted and did not hold. A proposal
with 1,045 rows and seven distinct values does not become a file.

*** SINGULAR TESTS, NOT schema.yml ENTRIES. ***
Measured on a real project: 344 of 358 models already have a schema yml entry, and a second entry
for the same model is a dbt compilation error. So a `schema.yml` patcher would break 96% of the
models it touched. A singular test is a `.sql` file that needs no entry anywhere, collides with
nothing, needs no `dbt_utils`, and can be deleted by deleting it.

*** AND IT NEVER OVERWRITES SOMETHING A PERSON EDITED. ***
Every file carries a marker. A file without it is left alone and reported, because the one thing
worse than a bad generated test is a generated test that ate a good handwritten one.
"""
from __future__ import annotations

import datetime as _dt
import re
from dataclasses import dataclass
from pathlib import Path

MARKER = "-- generated by assay. Edit freely: the marker below is what stops it being overwritten."
STAMP = "-- assay:generated"

_SAFE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


@dataclass
class Patch:
    model: str
    path: Path
    sql: str
    columns: list[str]
    rows: int
    distinct: int
    written: bool = False
    skipped: str = ""


def _ident(c: str) -> str:
    """A column name assay is willing to put in generated SQL.

    Anything that is not a plain identifier is refused rather than quoted-and-hoped: a generated
    file is read less carefully than a written one, and this is the wrong place to be clever.
    """
    return c if _SAFE.match(str(c)) else ""


def render(model: str, columns: list[str], rows: int, distinct: int, version: str) -> str:
    keys = ", ".join(columns)
    today = _dt.datetime.now(tz=_dt.timezone.utc).date().isoformat()
    return f"""{MARKER}
{STAMP} {version} {today}
--
-- One row per ({keys}) in `{model}`.
--
-- assay proposed this grain and COUNTED it before writing this file: {rows:,} rows,
-- {distinct:,} distinct. It held, so this test passes today. It is here to catch the day it
-- stops holding.
--
-- assay did not decide this was the RIGHT grain -- it inferred it from the SQL and checked the
-- arithmetic. If one row of `{model}` is something else, delete this file and say so in the
-- model's own documentation, where `assay claims` will pick it up.

select
    {keys},
    count(*) as n_rows
from {{{{ ref('{model}') }}}}
group by {keys}
having count(*) > 1
"""


def plan(patches: list, held: dict, version: str, out_dir: Path) -> list[Patch]:
    """What would be written, and for everything else, why not.

    `patches` is `practices.primary_key_patches` output; `held` is `practices.verify_grains`.
    A model absent from `held` was NOT COUNTED and is skipped -- an uncounted grain reading as a
    passing one is the defect this whole command exists to avoid.
    """
    out: list[Patch] = []
    for name, cols, _src, _marts, not_emitted in patches:
        target = out_dir / f"unique_{name}.sql"
        if not cols:
            out.append(Patch(name, target, "", [], 0, 0,
                             skipped="its grain is not in its own output, so no test can assert it"))
            continue
        if not_emitted:
            out.append(Patch(name, target, "", list(cols), 0, 0,
                             skipped=f"the grain names {', '.join(map(str, not_emitted))}, "
                                     f"which the model does not emit"))
            continue
        bad = [c for c in cols if not _ident(c)]
        if bad:
            out.append(Patch(name, target, "", list(cols), 0, 0,
                             skipped=f"{bad} is not a plain identifier; refusing to generate SQL"))
            continue
        counted = held.get(name)
        if counted is None:
            out.append(Patch(name, target, "", list(cols), 0, 0,
                             skipped="NOT COUNTED -- and an uncounted grain is not a passing one"))
            continue
        n, d = counted
        if d < n:
            out.append(Patch(name, target, "", list(cols), n, d,
                             skipped=f"it does not hold: {n:,} rows, {d:,} distinct "
                                     f"({n / max(d, 1):.0f}x). A test here fails on its first run"))
            continue
        out.append(Patch(name, target, render(name, list(cols), n, d, version),
                         list(cols), n, d))
    return out


def write(plans: list[Patch], out_dir: Path) -> tuple[int, list[Patch]]:
    """Write the ones that can be written. Returns (written, blocked_by_a_human_edit)."""
    blocked: list[Patch] = []
    n = 0
    out_dir.mkdir(parents=True, exist_ok=True)
    for p in plans:
        if not p.sql:
            continue
        if p.path.exists():
            try:
                existing = p.path.read_text()
            except OSError:
                existing = ""
            if STAMP not in existing:
                # *** NEVER EAT A HANDWRITTEN TEST. ***
                p.skipped = "a file is already there and assay did not write it"
                blocked.append(p)
                continue
        p.path.write_text(p.sql)
        p.written = True
        n += 1
    return n, blocked
